### ISSUE TITLE
Save to web by default is saving the entire psd as image

### ISSUE THREAD

**Issue by asafron** [RangelReale/htmlbutcher#1]
Hi.

By default, when creating a new project with the wizard, and than save to web, the entire PSD is saved as image. Can HTMLButcher automatically turn the PSD into detailed HTML (table based, with text etc.)?

Thanks.

**Comment by RangelReale** [comment]
No, it doesn't do anything automatically, you must draw lines and create
areas. These areas will be saved individually.
